import { useState } from "react";
import Head from "next/head";
import CarouselThumbs from "@components/CarouselThumbs";
import ProductImage from "@components/ProductImage";

const gallery = [
  { id: 1, imgUrl: "/images/Bed-1.webp" },
  { id: 2, imgUrl: "/images/Bed-2.webp" },
  { id: 3, imgUrl: "/images/Bed-3.webp" },
  { id: 4, imgUrl: "/images/Oak.webp" },
];

export default function Home() {
  const [thumbsSwiper, setThumbsSwiper] = useState(null);

  return (
    <div>
      <Head>
        <title>Product Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductImage gallery={gallery} thumbsSwiper={thumbsSwiper} />
      <CarouselThumbs gallery={gallery} setThumbsSwiper={setThumbsSwiper} />
    </div>
  );
}
